"use client"

import React from "react"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Loader2, Plus, X } from "lucide-react"
import { toast } from "sonner"
import type { ProductWithSizes } from "@/lib/types"

const JERSEY_SIZES = ["XS", "S", "M", "L", "XL", "XXL"]

type Props = {
  product?: ProductWithSizes
  mode: "create" | "edit"
}

export function ProductForm({ product, mode }: Props) {
  const router = useRouter()
  const [loading, setLoading] = useState(false)

  const [name, setName] = useState(product?.name ?? "")
  const [team, setTeam] = useState(product?.team ?? "")
  const [price, setPrice] = useState(product ? String(product.price) : "")
  const [category, setCategory] = useState(product?.category ?? "immediate")
  const [hasStock, setHasStock] = useState(product?.has_stock ?? true)
  const [imageUrl, setImageUrl] = useState(product?.image_url ?? "")
  const [imageUrl2, setImageUrl2] = useState(product?.image_url_2 ?? "")
  const [imageUrl3, setImageUrl3] = useState(product?.image_url_3 ?? "")
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [imageFile2, setImageFile2] = useState<File | null>(null)
  const [imageFile3, setImageFile3] = useState<File | null>(null)

  const [sizes, setSizes] = useState<{ size: string; stock: number }[]>(
    product?.product_sizes?.map((s) => ({
      size: s.size,
      stock: s.stock,
    })) ?? []
  )

  function addSize() {
    const availableSize = JERSEY_SIZES.find(
      (s) => !sizes.some((existing) => existing.size === s)
    )
    if (availableSize) {
      setSizes([...sizes, { size: availableSize, stock: 0 }])
    }
  }

  function removeSize(index: number) {
    setSizes(sizes.filter((_, i) => i !== index))
  }

  function updateSize(index: number, field: "size" | "stock", value: string) {
    const updated = [...sizes]
    if (field === "stock") {
      updated[index] = { ...updated[index], stock: parseInt(value) || 0 }
    } else {
      updated[index] = { ...updated[index], size: value }
    }
    setSizes(updated)
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)

    try {
      const supabase = createClient()

      // Upload images if files selected
      const uploadImage = async (file: File | null, currentUrl: string) => {
        if (!file) return currentUrl
        const ext = file.name.split(".").pop()
        const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${ext}`
        const { data: uploadData, error: uploadError } = await supabase.storage
          .from("product-images")
          .upload(fileName, file)

        if (uploadError) throw uploadError

        const {
          data: { publicUrl },
        } = supabase.storage
          .from("product-images")
          .getPublicUrl(uploadData.path)
        return publicUrl
      }

      const finalImageUrl = await uploadImage(imageFile, imageUrl)
      const finalImageUrl2 = await uploadImage(imageFile2, imageUrl2)
      const finalImageUrl3 = await uploadImage(imageFile3, imageUrl3)

      const productData = {
        name,
        team: team || null,
        price: parseFloat(price),
        category,
        has_stock: hasStock,
        image_url: finalImageUrl || null,
        image_url_2: finalImageUrl2 || null,
        image_url_3: finalImageUrl3 || null,
      }

      if (mode === "create") {
        const { data: newProduct, error } = await supabase
          .from("products")
          .insert({ ...productData, code: "TEMP" }) // code is auto-generated by trigger
          .select()
          .single()

        if (error) throw error

        // Add sizes
        if (sizes.length > 0) {
          const { error: sizeError } = await supabase
            .from("product_sizes")
            .insert(
              sizes.map((s) => ({
                product_id: newProduct.id,
                size: s.size,
                stock: s.stock,
              }))
            )
          if (sizeError) throw sizeError
        }

        toast.success("Producto creado exitosamente")
      } else if (product) {
        const { error } = await supabase
          .from("products")
          .update(productData)
          .eq("id", product.id)

        if (error) throw error

        // Delete existing sizes and re-insert
        await supabase
          .from("product_sizes")
          .delete()
          .eq("product_id", product.id)

        if (sizes.length > 0) {
          const { error: sizeError } = await supabase
            .from("product_sizes")
            .insert(
              sizes.map((s) => ({
                product_id: product.id,
                size: s.size,
                stock: s.stock,
              }))
            )
          if (sizeError) throw sizeError
        }

        toast.success("Producto actualizado exitosamente")
      }

      router.push("/admin/productos")
      router.refresh()
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Error al guardar el producto"
      )
    } finally {
      setLoading(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-foreground">Informacion del Producto</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <Label htmlFor="name">Nombre *</Label>
              <Input
                id="name"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Camiseta Barcelona 24/25"
                className="mt-1"
              />
            </div>
            <div>
              <Label htmlFor="team">Equipo</Label>
              <Input
                id="team"
                value={team}
                onChange={(e) => setTeam(e.target.value)}
                placeholder="FC Barcelona"
                className="mt-1"
              />
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <Label htmlFor="price">Precio *</Label>
              <Input
                id="price"
                type="number"
                step="0.01"
                min="0"
                required
                value={price}
                onChange={(e) => setPrice(e.target.value)}
                placeholder="29.99"
                className="mt-1"
              />
            </div>
            <div>
              <Label>Categoria *</Label>
              <Select value={category} onValueChange={(val) => setCategory(val as any)}>
                <SelectTrigger className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="immediate">Entrega Inmediata</SelectItem>
                  <SelectItem value="preorder">Pedido Previo</SelectItem>
                  <SelectItem value="accessory">Accesorio</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <Switch
              id="has-stock"
              checked={hasStock}
              onCheckedChange={setHasStock}
            />
            <Label htmlFor="has-stock">Producto disponible</Label>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-foreground">Imágenes</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-3 p-4 border rounded-lg bg-muted/50">
            <h3 className="text-sm font-medium">Imagen Principal</h3>
            <div>
              <Label htmlFor="image-file">Subir imagen</Label>
              <Input
                id="image-file"
                type="file"
                accept="image/*"
                onChange={(e) => setImageFile(e.target.files?.[0] ?? null)}
                className="mt-1 bg-background"
              />
            </div>
            <div>
              <Label htmlFor="image-url">O pegar URL</Label>
              <Input
                id="image-url"
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
                placeholder="https://..."
                className="mt-1 bg-background"
              />
            </div>
          </div>

          <div className="space-y-3 p-4 border rounded-lg bg-muted/50">
            <h3 className="text-sm font-medium">Imagen 2</h3>
            <div>
              <Label htmlFor="image-file-2">Subir imagen</Label>
              <Input
                id="image-file-2"
                type="file"
                accept="image/*"
                onChange={(e) => setImageFile2(e.target.files?.[0] ?? null)}
                className="mt-1 bg-background"
              />
            </div>
            <div>
              <Label htmlFor="image-url-2">O pegar URL</Label>
              <Input
                id="image-url-2"
                value={imageUrl2}
                onChange={(e) => setImageUrl2(e.target.value)}
                placeholder="https://..."
                className="mt-1 bg-background"
              />
            </div>
          </div>

          <div className="space-y-3 p-4 border rounded-lg bg-muted/50">
            <h3 className="text-sm font-medium">Imagen 3</h3>
            <div>
              <Label htmlFor="image-file-3">Subir imagen</Label>
              <Input
                id="image-file-3"
                type="file"
                accept="image/*"
                onChange={(e) => setImageFile3(e.target.files?.[0] ?? null)}
                className="mt-1 bg-background"
              />
            </div>
            <div>
              <Label htmlFor="image-url-3">O pegar URL</Label>
              <Input
                id="image-url-3"
                value={imageUrl3}
                onChange={(e) => setImageUrl3(e.target.value)}
                placeholder="https://..."
                className="mt-1 bg-background"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-foreground">Tallas y Stock</CardTitle>
          <Button type="button" variant="outline" size="sm" onClick={addSize}>
            <Plus className="mr-1 h-4 w-4" />
            Agregar Talla
          </Button>
        </CardHeader>
        <CardContent>
          {sizes.length === 0 ? (
            <p className="py-4 text-center text-sm text-muted-foreground">
              No se han agregado tallas
            </p>
          ) : (
            <div className="space-y-3">
              {sizes.map((s, i) => (
                <div key={i} className="flex items-center gap-3">
                  <Select
                    value={s.size}
                    onValueChange={(val) => updateSize(i, "size", val)}
                  >
                    <SelectTrigger className="w-24">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {JERSEY_SIZES.map((size) => (
                        <SelectItem key={size} value={size}>
                          {size}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <div className="flex items-center gap-2">
                    <Label className="text-sm text-muted-foreground">Stock:</Label>
                    <Input
                      type="number"
                      min="0"
                      value={s.stock}
                      onChange={(e) => updateSize(i, "stock", e.target.value)}
                      className="w-20"
                    />
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 text-muted-foreground hover:text-destructive"
                    onClick={() => removeSize(i)}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      <div className="flex gap-3">
        <Button type="submit" disabled={loading}>
          {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          {mode === "create" ? "Crear Producto" : "Guardar Cambios"}
        </Button>
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push("/admin/productos")}
        >
          Cancelar
        </Button>
      </div>
    </form>
  )
}
